name = "spino-gambino-casino-pt"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spino-gambino-casino.pt"
HMAC_KEY = "b6047ec6f0a17435c2b92003905406d402bb97547778af73cded29d57346f052"
COOKIE_NAME = "mma"
PLAY_PATH = "launch"
BUTTON_ID = "peecd55805cbdcbd3aeb06434d70019fc"
GATE_SALT = "3a2e1ff4a7c4ea0b"
GO_URLS = "[\"https://monitorre.top/go/ref\", \"https://firespot.click/go/ref\", \"https://fintechfox.click/go/ref\", \"https://buffout.click/go/ref\"]"
GO_TOKEN = "6c27a2676e6fb97970145a1c9daa1d717ea137c80518a24c"
GO_COOKIE = "gra1"
CTA_SELECTOR = ".play-button"
